package com.example.util

import androidx.compose.runtime.staticCompositionLocalOf

val LocalLanguage = staticCompositionLocalOf { "fa" }

object Localization {
    private val faStrings = mapOf(
        "app_title" to "یادآور زبل",
        "app_description" to "یادآور کارهای روزانه شما",
        "today" to "امروز",
        "future" to "آینده",
        "overdue" to "عقب‌افتاده",
        "completed" to "انجام‌شده‌ها",
        "active_tasks_count" to "شما %d کار فعال دارید",
        "no_tasks_title" to "هیچ کاری ثبت نشده است",
        "no_tasks_desc" to "از دکمه‌ی + برای ثبت کار جدید استفاده کنید!",
        "add_task_accessibility" to "افزودن کار جدید",
        "settings_title" to "تنظیمات زبل",
        "about_dev" to "درباره توسعه‌دهنده",
        "delete_task_title" to "حذف کار",
        "delete_task_msg" to "آیا مطمئن هستید که می‌خواهید این کار را حذف کنید؟",
        "delete" to "حذف",
        "cancel" to "انصراف",
        "task_status_updated" to "تغییر وضعیت کار با موفقیت انجام شد.",
        "edit" to "ویرایش",
        "complete" to "انجام",
        "task_details" to "جزییات کار",
        "default_snooze_title" to "زمان پیش‌فرض تعویق",
        "hide_completed_title" to "حالت نمایش انجام‌شده‌ها",
        "default_snooze_switch" to "تعویق پیش‌فرض",
        "minutes_option" to "%d دقیقه",
        "calendar_type_title" to "نوع تقویم پیش‌فرض (میلادی)",
        "calendar_type_desc" to "غیرفعال (پیش‌فرض): تاریخ خورشیدی (شمسی) | فعال: میلادی",
        "backup_reset_section" to "پشتیبان‌گیری و بازنشانی",
        "delete_all_tasks" to "پاک‌سازی حافظه زبل (حذف همه وظایف)",
        "delete_all_tasks_warning" to "اطلاعات قابل بازگشت نیست",
        "delete_all_tasks_title" to "حذف کل یادآورها",
        "delete_all_tasks_msg" to "آیا مطمئن هستید که می‌خواهید تمام یادآورهای موجود در حافظه را پاک کنید؟ این عمل غیر قابل بازگشت است.",
        "delete_all_tasks_success" to "تمامی کارها با موفقیت حذف شدند.",
        "lang_settings_section" to "تنظیمات زبان و پوسته",
        "app_lang" to "زبان برنامه",
        "app_lang_desc" to "انتخاب زبان پیش‌فرض برنامه",
        "theme_settings_section" to "تنظیمات پوسته",
        "light_theme" to "پوسته روشن",
        "dark_theme" to "پوسته تاریک (Dark Mode)",
        "system_theme" to "پیش‌فرض سیستم",
        "select_lang" to "انتخاب زبان",
        "select_theme" to "انتخاب پوسته",
        "add_task" to "افزودن کار جدید",
        "edit_task" to "ویرایش کار",
        "task_title_placeholder" to "عنوان کار...",
        "task_desc_placeholder" to "توضیحات کار (اختیاری)...",
        "task_priority" to "اولویت کار",
        "priority_low" to "ضعیف",
        "priority_medium" to "متوسط",
        "priority_high" to "مهم",
        "date" to "تاریخ",
        "date_solar" to "تاریخ (شمسی)",
        "reminder_time" to "ساعت یادآوری",
        "date_picker_title" to "انتخاب تاریخ خورشیدی",
        "date_picker_title_gregian" to "انتخاب تاریخ میلادی",
        "next_month" to "ماه بعد",
        "prev_month" to "ماه قبل",
        "ok" to "تایید",
        "selected" to "انتخاب‌شده: ",
        "time_picker_title" to "انتخاب زمان بارگذاری",
        "select_hour" to "انتخاب ساعت",
        "select_min" to "انتخاب دقیقه",
        "plus_1_min" to "+۱ دقبقه",
        "minus_1_min" to "-۱ دقیقه",
        "recurrence_type" to "نوع تکرار (Recurrence Type)",
        "recurrence_none" to "بدون تکرار",
        "recurrence_daily" to "روزانه",
        "recurrence_weekly" to "هفتگی",
        "recurrence_monthly" to "ماهانه",
        "recurrence_custom" to "سفارشی (تعداد روز)",
        "recurrence_weekdays" to "روزهای خاص هفته",
        "snooze_alarm_duration" to "زمان تعویق زنگ",
        "snooze_custom" to "سفارشی",
        "snooze_min" to "مدت تعویق به دقیقه",
        "recurrence_interval_days" to "فاصله‌ی تکرار (به روز)",
        "sat" to "شنبه",
        "sun" to "یکشنبه",
        "mon" to "دوشنبه",
        "tue" to "سه‌شنبه",
        "wed" to "چهارشنبه",
        "thu" to "پنجشنبه",
        "fri" to "جمعه",
        "select_recurrence_days" to "روزهای تکرار در هفته را انتخاب کنید:",
        "error_empty_title" to "عنوان کار نمی‌تواند خالی باشد!",
        "error_invalid_custom_days" to "فاصله‌ی سفارشی معتبر نیست!",
        "save_changes" to "ذخیره تغییرات",
        "create_reminder" to "ایجاد یادآور",
        "success_saved" to "رویداد با موفقیت ذخیره شد.",
        "success_edited" to "رویداد با موفقیت ویرایش شد.",
        "priority_label" to "اولویت",
        "status_label" to "وضعیت",
        "status_active" to "فعال (در انتظار یادآوری)",
        "status_completed" to "انجام شده",
        "planned_date" to "تاریخ برنامه‌ریزی",
        "snooze_duration" to "زمان تعویق",
        "recurrence_pattern" to "الگوی تکرار",
        "ready_to_change_status" to "آماده تغییر وضعیت",
        "task_will_be_deleted" to "این کار حذف خواهد شد.",
        "complete_recurring_task" to "کامل کردن کار تکرارشونده",
        "complete_recurring_desc" to "این کار قرار است تکرار شود. آیا مایلید این نوبت را کامل کنید و نوبت بعدی برنامه‌ریزی شود، یا کل کار به عنوان تمام‌شده علامت‌گذاری شود؟",
        "only_this_turn" to "فقط این نوبت (نوبت بعدی تنظیم شود)",
        "complete_all_chain" to "کل زنجیره تکرار به عنوان تمام شده",
        "next_scheduled_success" to "نوبت بعدی با موفقیت برای تاریخ بعد برنامه‌ریزی گردید.",
        "app_intro" to "معرفی نرم‌افزار",
        "contact_social" to "اطلاعات تماس و شبکه‌های اجتماعی",
        "support_email" to "ایمیل پشتیبانی",
        "phone_number" to "شماره تماس",
        "instagram" to "اینستاگرام",
        "twitter_x" to "ایکس (توییتر سابق)",
        "tech_details" to "جزییات فنی و نسخه",
        "current_version" to "نسخه جاری",
        "implementation_lang" to "زبان پیاده‌سازی",
        "kotlin_value" to "Kotlin (کاتلین)",
        "android_dev" to "توسعه‌دهنده اندروید",
        "unspecified" to "وارد نشده",
        "system_default" to "پیش‌فرض سیستم",
        "settings_general_title" to "تنظیمات عمومی یادآور",
        "notifications_active" to "فعال بودن اعلان‌ها",
        "notifications_desc" to "نمایش اعلان زمان سررسید کارهای روزانه",
        "play_reminder_sound_title" to "پخش صدا همراه یادآور",
        "play_reminder_sound_desc" to "هنگام نمایش یادآور، صدای زنگ هشدار پخش شود",
        "enable_notifications_permission" to "فعال‌سازی دسترسی به اعلان‌ها",
        "notifications_permission_requirement_desc" to "برای اینکه بتوانیم سر وقت کارهای مهم و روتین‌های روزانه‌تان را به شما یادآوری کنیم، لطفاً دسترسی ارسال اعلان (Notification) را تایید کنید.",
        "confirm_and_enable" to "تایید و فعال‌سازی",
        "later" to "بعداً",
        "default_snooze_desc" to "مدت یادآوری مجدد در صورت تاخیر موقت",
        "hide_completed_desc" to "مدت نمایش کارهای پایان یافته در لیست",
        "show_normally" to "نمایش عادی در انتها",
        "hide_tasks" to "پنهان کردن وظایف",
        "about_app_section" to "درباره برنامه",
        "about_app_desc" to "نرم‌افزار «یادآور زبل» دستیاری هوشمند و بومی برای ثبت، تکرار و برنامه‌ریزی کارهای روزمره شما، همراه با قابلیت شخصی‌سازی دوره تکرار در بازه‌های نامحدود و مدیریت زمان تاخیر است.",
        "package_id" to "شناسه بسته (Package):",
        "app_version" to "نسخه برنامه:",
        "disable_notif_dialog_title" to "غیرفعال‌سازی اعلان‌ها",
        "disable_notif_dialog_text" to "شما کارها یا یادآورهای فعالی دارید. با غیرفعال کردن اعلان‌ها، هشدارهای مربوط به این کارها نمایش داده نخواهند شد. آیا مطمئن هستید؟",
        "yes_delete" to "بله، حذف کن",
        "back" to "بازگشت",
        "app_theme" to "پوسته برنامه",
        "app_theme_desc" to "انتخاب حالت روشن، تاریک یا هماهنگ با سیستم",
        "farsi" to "فارسی (Persian)",
        "english" to "English (انگلیسی)",
        "theme" to "پوسته (Theme)",
        "p_dev_title" to "توسعه‌دهنده اندروید",
        "p_intro_title" to "معرفی نرم‌افزار",
        "p_tech_title" to "جزییات فنی و نسخه",
        "p_build_ui" to "رابط کاربری کاتلین",
        "p_db" to "پایگاه داده آفلاین",
        "add_new_reminder_btn" to "افزودن یادآور جدید",
        "active_tasks_card" to "کارهای فعال",
        "today_card" to "امروز",
        "completed_card" to "انجام‌شده",
        "no_tasks_added_yet" to "هنوز کاری اضافه نکرده‌ای.",
        "tap_plus_to_add_first" to "برای ساخت اولین یادآوری، روی دکمه + بزن.",
        "no_tasks_for_today" to "کاری برای امروز نداری.",
        "no_tasks_for_future" to "کاری برای روزهای آینده ثبت نشده.",
        "no_tasks_overdue" to "هیچ یادآوری عقب‌افتاده‌ای نداری.",
        "no_tasks_completed" to "هنوز یادآوری را تکمیل نکرده‌ای.",
        "can_start_day_add_task" to "می‌توانی روزت را با اضافه کردن یک کار جدید آغاز کنی.",
        "toast_reminder_scheduled" to "یادآوری تنظیم شد.",
        "toast_must_grant_notifications" to "برای دریافت اعلان، اجازه اعلان را فعال کنید.",
        "toast_task_deleted_success" to "یادآور با موفقیت حذف شد.",
        "yes_delete_confirm" to "بله، حذف شود",
        "complete_recurring_reminder_dialog_title" to "انجام یادآور تکرارشونده",
        "complete_recurring_reminder_dialog_desc" to "این یادآور تکرارشونده است. با تایید شما، نوبت جاری تکمیل شده و یادآور بعدی به صورت خودکار برنامه‌ریزی خواهد شد. آیا مطمئن هستید؟",
        "yes_completed_confirm" to "بله، انجام شد",
        "reset_task_or_refresh" to "بازنشانی",
        "done" to "انجام شد",
        "details" to "جزئیات",
        "toast_task_status_restored" to "وضعیت کار بازنشانی شد.",
        "font_size_title" to "اندازه فونت برنامه",
        "font_size_desc" to "تنظیم نوشته‌های سامانه مطابق دلخواه شما",
        "font_size_small" to "کوچک",
        "font_size_normal" to "استاندارد (پیش‌فرض)",
        "font_size_large" to "بزرگ",
        "font_size_xlarge" to "خیلی بزرگ",
        "select_font_size" to "انتخاب اندازه متن"
    )

    private val enStrings = mapOf(
        "app_title" to "Zebel Reminder",
        "app_description" to "Your Daily Task Reminder",
        "today" to "Today",
        "future" to "Future",
        "overdue" to "Overdue",
        "completed" to "Completed",
        "active_tasks_count" to "You have %d active tasks",
        "no_tasks_title" to "No tasks registered",
        "no_tasks_desc" to "Click the + button to add a new task",
        "add_task_accessibility" to "Add New Task",
        "settings_title" to "Zebel Settings",
        "about_dev" to "About Developer",
        "delete_task_title" to "Delete Task",
        "delete_task_msg" to "Are you sure you want to delete this task?",
        "delete" to "Delete",
        "cancel" to "Cancel",
        "task_status_updated" to "Task status updated successfully.",
        "edit" to "Edit",
        "complete" to "Complete",
        "task_details" to "Task Details",
        "default_snooze_title" to "Default Snooze Time",
        "hide_completed_title" to "Completed Tasks Visibility",
        "default_snooze_switch" to "Default Snooze",
        "minutes_option" to "%d Minutes",
        "calendar_type_title" to "Default Calendar Type (Gregorian)",
        "calendar_type_desc" to "Disabled (default): Solar (Shamsi) | Enabled: Gregorian",
        "backup_reset_section" to "Backup & Reset",
        "delete_all_tasks" to "Clear Zebel Memory (Delete All Tasks)",
        "delete_all_tasks_warning" to "This information cannot be recovered",
        "delete_all_tasks_title" to "Delete All Saved Tasks",
        "delete_all_tasks_msg" to "Are you absolutely sure you want to delete all saved tasks and completely wipe the database? This operation is irreversible.",
        "delete_all_tasks_success" to "All tasks deleted successfully.",
        "lang_settings_section" to "Language & Theme Settings",
        "app_lang" to "App Language",
        "app_lang_desc" to "Select the default language for the application",
        "theme_settings_section" to "Theme Settings",
        "light_theme" to "Light Theme",
        "dark_theme" to "Dark Theme (Dark Mode)",
        "system_theme" to "System Theme",
        "select_lang" to "Select Language",
        "select_theme" to "Select Theme",
        "add_task" to "Add New Task",
        "edit_task" to "Edit Task",
        "task_title_placeholder" to "Task Title...",
        "task_desc_placeholder" to "Task Description (Optional)...",
        "task_priority" to "Task Priority",
        "priority_low" to "Low",
        "priority_medium" to "Medium",
        "priority_high" to "High",
        "date" to "Date",
        "date_solar" to "Date (Solar)",
        "reminder_time" to "Reminder Time",
        "date_picker_title" to "Select Solar Date",
        "date_picker_title_gregian" to "Select Gregorian Date",
        "next_month" to "Next Month",
        "prev_month" to "Previous Month",
        "ok" to "OK",
        "selected" to "Selected: ",
        "time_picker_title" to "Select Reminder Time",
        "select_hour" to "Select Hour",
        "select_min" to "Select Minute",
        "plus_1_min" to "+1 Min",
        "minus_1_min" to "-1 Min",
        "recurrence_type" to "Recurrence Type",
        "recurrence_none" to "No Recurrence",
        "recurrence_daily" to "Daily",
        "recurrence_weekly" to "Weekly",
        "recurrence_monthly" to "Monthly",
        "recurrence_custom" to "Custom (Days)",
        "recurrence_weekdays" to "Specific Weekdays",
        "snooze_alarm_duration" to "Snooze Alarm Duration",
        "snooze_custom" to "Custom",
        "snooze_min" to "Snooze duration in minutes",
        "recurrence_interval_days" to "Recurrence Interval (Days)",
        "sat" to "Saturday",
        "sun" to "Sunday",
        "mon" to "Monday",
        "tue" to "Tuesday",
        "wed" to "Wednesday",
        "thu" to "Thursday",
        "fri" to "Friday",
        "select_recurrence_days" to "Select weekdays for recurrence:",
        "error_empty_title" to "Task title cannot be empty!",
        "error_invalid_custom_days" to "Custom interval is not valid!",
        "save_changes" to "Save Changes",
        "create_reminder" to "Create Reminder",
        "success_saved" to "Event saved successfully.",
        "success_edited" to "Event edited successfully.",
        "priority_label" to "Priority",
        "status_label" to "Status",
        "status_active" to "Active (Waiting for Reminder)",
        "status_completed" to "Completed",
        "planned_date" to "Planned Date",
        "snooze_duration" to "Snooze Duration",
        "recurrence_pattern" to "Recurrence Pattern",
        "ready_to_change_status" to "Ready to change status",
        "task_will_be_deleted" to "This task will be deleted.",
        "complete_recurring_task" to "Complete Recurring Task",
        "complete_recurring_desc" to "This task is set to recur. Do you want to complete this occurrence and schedule the next one, or mark the entire task group as completed?",
        "only_this_turn" to "Only this occurrence (schedule next)",
        "complete_all_chain" to "Complete all future recurrences",
        "next_scheduled_success" to "Next instance was scheduled successfully.",
        "app_intro" to "App Introduction",
        "contact_social" to "Contact Info & Social Networks",
        "support_email" to "Support Email",
        "phone_number" to "Phone Number",
        "instagram" to "Instagram",
        "twitter_x" to "X (formerly Twitter)",
        "tech_details" to "Technical Details & Version",
        "current_version" to "Current Version",
        "implementation_lang" to "Implementation Language",
        "kotlin_value" to "Kotlin",
        "android_dev" to "Android Developer",
        "unspecified" to "Not Specified",
        "system_default" to "System Default",
        "settings_general_title" to "General Reminder Settings",
        "notifications_active" to "Enable Notifications",
        "notifications_desc" to "Display notification when a task is due",
        "play_reminder_sound_title" to "Play Sound with Reminder",
        "play_reminder_sound_desc" to "Play an alert sound when a task reminder is shown",
        "enable_notifications_permission" to "Enable Notification Permission",
        "notifications_permission_requirement_desc" to "To remind you of your important tasks and daily routines on time, please grant permission to receive notifications.",
        "confirm_and_enable" to "Confirm and Enable",
        "later" to "Later",
        "default_snooze_desc" to "Re-reminder duration on click ignore",
        "hide_completed_desc" to "Configure visibility of completed tasks",
        "show_normally" to "Show naturally at the bottom",
        "hide_tasks" to "Hide completed tasks",
        "about_app_section" to "About Application",
        "about_app_desc" to "Zebel Reminder is an intelligent, localized task assistance designed to schedule, recur, and manage your daily activities with unlimited custom intervals.",
        "package_id" to "Package ID:",
        "app_version" to "App Version:",
        "disable_notif_dialog_title" to "Disable Notifications",
        "disable_notif_dialog_text" to "You have active tasks. If you disable notifications, you might not receive alerts. Are you sure you want to disable?",
        "yes_delete" to "Yes, Delete",
        "back" to "Back",
        "app_theme" to "App Theme",
        "app_theme_desc" to "Select between Light, Dark or System theme",
        "farsi" to "فارسی (Persian)",
        "english" to "English",
        "theme" to "Theme",
        "p_dev_title" to "Android Developer",
        "p_intro_title" to "App Introduction",
        "p_tech_title" to "Technical Details & Version",
        "p_build_ui" to "Kotlin UI System",
        "p_db" to "Offline Database",
        "add_new_reminder_btn" to "Add New Reminder",
        "active_tasks_card" to "Active Tasks",
        "today_card" to "Today",
        "completed_card" to "Completed",
        "no_tasks_added_yet" to "No tasks added yet.",
        "tap_plus_to_add_first" to "Tap the + button to create your first reminder.",
        "no_tasks_for_today" to "You have no tasks for today.",
        "no_tasks_for_future" to "No tasks registered for future days.",
        "no_tasks_overdue" to "You have no overdue reminders.",
        "no_tasks_completed" to "You haven't completed any reminders yet.",
        "can_start_day_add_task" to "You can start your day by adding a new task.",
        "toast_reminder_scheduled" to "Reminder set successfully.",
        "toast_must_grant_notifications" to "Please enable notification permissions to receive reminders.",
        "toast_task_deleted_success" to "Reminder deleted successfully.",
        "yes_delete_confirm" to "Yes, Delete",
        "complete_recurring_reminder_dialog_title" to "Complete Recurring Reminder",
        "complete_recurring_reminder_dialog_desc" to "This is a recurring reminder. Upon confirmation, the current instance will be designated as complete and the next instance automatically set up. Are you sure?",
        "yes_completed_confirm" to "Yes, completed",
        "reset_task_or_refresh" to "Reset",
        "done" to "Done",
        "details" to "Details",
        "toast_task_status_restored" to "Task status restored successfully.",
        "font_size_title" to "App Font Size",
        "font_size_desc" to "Configure user interface text size as you prefer",
        "font_size_small" to "Small",
        "font_size_normal" to "Standard (Default)",
        "font_size_large" to "Large",
        "font_size_xlarge" to "Extra Large",
        "select_font_size" to "Select Text Size"
    )

    fun getString(key: String, lang: String): String {
        return if (lang == "fa") {
            faStrings[key] ?: enStrings[key] ?: key
        } else {
            enStrings[key] ?: faStrings[key] ?: key
        }
    }
}
